spring:
  application:
    name: Gateway-Service
#  cloud:
#    gateway:
#      routes:
#        - id: after_route
#          uri: https://example.org
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]


  config:
    import: optional:configserver:http://localhost:7002





