spring:
  application:
    name: Gateway-Service


  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:7003
          predicates:
            - Path=/api/v1/auth/**
        - id: post-service
          uri: http://localhost:7004
          predicates:
            - Path=/post/**
          filters:
            - AuthenticationFilter






server:
  port: 7000


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


security:
  jwt:
    token:
      secret-key: 6b92c32a9619a918caa8a54fde6d3952e6337d56587db1130491793235efc74e
      secret-key-api-gateway: e98d042883db642293c46a09c508231f6a41870897eaaf33c2986de0e2899b2c


