spring:

  application:
    name: User-Service
  jpa:
    hibernate:
          ddl-auto: update

  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.xhuxtaljeyejxiraeelg
    password: tvMsC4YcgdlladlO
  config:
    import: optional:configserver:http://localhost:7002




eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
server:
  port: 7003
